### ISSUE TITLE
Retention анализ

### ISSUE THREAD

**Issue by Artem2001S** [doochik/react-native-appmetrica#59]
В Retenton-анализ отсутствуют данные

Поддерживает ли данная версия библиотеки сбор статистики для составления Retention-анализа ?

**Comment by ghost** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 16968574. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp19.04.2022, 21:08, "Artem2001S" ***@***.***>:
В Retenton-анализ отсутствуют данные
Поддерживает ли данная версия библиотеки сбор статистики для составления Retention-анализа ?

**Comment by ghost** [comment]
Добрый день!

Напишите нам, пожалуйста, напрямую в форму обратной связи: https://appmetrica.yandex.com/docs/troubleshooting/feedback.html 
С указанием ID вашего приложения. Поможем разобраться.

С уважением, команда AppMetrica.
